version: '3.4'

services:

  postgres:
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sql      
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/  
      
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@tamagotchi.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  web.httpaggregator:
    container_name: web.httpaggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
      - "Tamagotchi_RabbitMq__Host=amqp://guest:guest@rabbitmq:5672"
      - "Tamagotchi_Urls__RestaurantsGrpc=http://restaurants.api"
      - "Tamagotchi_Urls__OrdersGrpc=http://orders.api"
      - "Tamagotchi_Urls__OrderQueueGrpc=http://orderqueue.api"
      - "Tamagotchi_Urls__DishesGrpc=http://menu.api"
      - "Tamagotchi_Urls__MenuGrpc=http://menu.api"
      - "Tamagotchi_Urls__TablesGrpc=http://tables.api"
      - "Tamagotchi_Urls__ResourcesGrpc=http://resources.api"
      - "Tamagotchi_ElasticConfiguration__Uri=http://elasticsearch:9200"
      - "Tamagotchi_MinIO__ConnectionString=s3://minio:minio_password@minio:9000"
      - "Tamagotchi_Authenticate__Secret=S5yasF5y3S5aQjJKkUf0ElrTcdmpPrp6KNC64eYkQUtSayhqTXhKnCVrgIhsNakwPKa0GecTHRGDRFtjC-Mf3upA2o4t0BmlIiN_Zb01n-835OLASgqKrq6by3lVhYuu-e5O4N8oqVEMgaUmfHmFcC6YIigNl__g5IG4jgg1b9g"
    ports:
      - "5000:80"      
  
  orderqueue.api:
    container_name: orderqueue.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Tamagotchi_RabbitMq__Host=amqp://guest:guest@rabbitmq:5672"
      - "Tamagotchi_ConnectionStrings__OrderQueueDb=Server=postgres;Port=5432;Database=order_queue;User Id=postgres;Password=sql"    
    ports:
      - "5010:80"
  
  orders.api:
    container_name: orders.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "Tamagotchi_RabbitMq__Host=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "5011:80"         

  restaurants.api:
    container_name: restaurants.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  
      - "Tamagotchi_ConnectionStrings__RestaurantsDb=Server=postgres;Port=5432;Database=tamagotchi_restaurants;User Id=postgres;Password=sql"    
      - "Tamagotchi_Geocoding__GeocodingGrpc=http://geocoding.api"
    ports:
      - "5012:80"
      
  menu.api:
    container_name: menu.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  
      - "Tamagotchi_ConnectionStrings__MenuDb=Server=postgres;Port=5432;Database=tamagotchi_menu;User Id=postgres;Password=sql"    
      - "Tamagotchi_Restaurants__RestaurantsGrpc=http://restaurants.api"
    ports:
      - "5013:80"

  geocoding.api:
    container_name: geocoding.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  
      - "Tamagotchi_Geocoding__UseGeocoding=false"
      - "Tamagotchi_Geocoding__GoogleApiKey=${Tamagotchi_Geocoding__GoogleApiKey}"
      - "Tamagotchi_Geocoding__Language=ru"
      - "Tamagotchi_Geocoding__RedisCache=redis"
    ports:
      - "5014:80"

  tables.api:
    container_name: tables.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  
      - "Tamagotchi_ConnectionStrings__TablesDb=Server=postgres;Port=5432;Database=tamagotchi_tables;User Id=postgres;Password=sql"    
      - "Tamagotchi_Restaurants__RestaurantsGrpc=http://restaurants.api"
    ports:
      - "5015:80"

  management.ui:
    container_name: management.ui
    ports:
      - "5005:80"
  restaurant.ui:
    container_name: restaurant.ui
    ports:
      - "5006:80"
  orders.ui:
    container_name: orders.ui
    ports:
      - "5007:80"

  minio:
    container_name: minio
    volumes:
      - minio_data:/data

  mongo:
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  mongo-express:
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/

  resources.api:
    container_name: resources.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  
      - "Tamagotchi_ResourcesDatabase__ConnectionString=mongodb://root:password@mongo:27017/"    
      - "Tamagotchi_ResourcesDatabase__DatabaseName=ResourcesStore"    
      - "Tamagotchi_ResourcesDatabase__ResourcesCollectionName=Resources"
      - "Tamagotchi_RabbitMq__Host=amqp://guest:guest@rabbitmq:5672"
      - "Tamagotchi_MinIO__ConnectionString=s3://minio:minio_password@minio:9000"
    ports:
      - "5016:80"

