version: '3.4'

services:

  postgres:
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sql      
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data/  
      
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@tamagotchi.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"

  web.httpaggregator:
    container_name: web.httpaggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
      - "Tamagotchi_RabbitMq__Host=amqp://guest:guest@rabbitmq:5672"
      - "Tamagotchi_Urls__RestaurantsGrpc=http://restaurants.api"
      - "Tamagotchi_Urls__OrdersGrpc=http://orders.api"
      - "Tamagotchi_Urls__OrderQueueGrpc=http://orderqueue.api"
      - "Tamagotchi_ElasticConfiguration__Uri=http://elasticsearch:9200"
    ports:
      - "5000:80"      
  
  orderqueue.api:
    container_name: orderqueue.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "RabbitMq:Host=amqp://guest:guest@rabbitmq:5672"
      - "ConnectionStrings:OrderQueueDb=Server=postgres;Port=5432;Database=order_queue;User Id=postgres;Password=sql"    
    ports:
      - "6005:80"
  
  orders.api:
    container_name: orders.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "RabbitMq:Host=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "10000:80"         

  restaurants.api:
    container_name: restaurants.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  
      - "ConnectionStrings:Npgsql=Server=postgres;Port=5432;Database=tamagotchi_restaurants;User Id=postgres;Password=sql"    
    ports:
      - "6000:80"     
