version: '3.4'

services:

  elasticsearch:
   container_name: elasticsearch
   image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
   ports:
    - 9200:9200
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
   environment:
    - xpack.monitoring.enabled=true
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node

  kibana:
   container_name: kibana
   image: docker.elastic.co/kibana/kibana:7.9.2
   ports:
    - 5601:5601
   depends_on:
    - elasticsearch
   environment:
    - ELASTICSEARCH_URL=http://elasticsearch
    #- ELASTICSEARCH_URL=http://localhost:9200

  pgadmin:
    image: dpage/pgadmin4
    
  postgres:
    image: postgres    

  rabbitmq:
    image: rabbitmq:3-management-alpine

  redis:
    image: "redis:alpine"

  web.httpaggregator:
    image: ${DOCKER_REGISTRY-}webhttpaggregator
    build:
      context: .
      dockerfile: ApiGateways/Web.HttpAggregator/aggregator/Web.HttpAggregator/Dockerfile
    depends_on:
      - rabbitmq
      - elasticsearch

  orderqueue.api:
    image: ${DOCKER_REGISTRY-}orderqueueapi
    build:
      context: .
      dockerfile: Services/OrderQueue/OrderQueue.API/Dockerfile
    depends_on:
      - rabbitmq
      - postgres

  orders.api:
    image: ${DOCKER_REGISTRY-}ordersapi
    build:
      context: .
      dockerfile: Services/Orders/Orders.API/Dockerfile
    depends_on:
      - rabbitmq

  restaurants.api:
    image: ${DOCKER_REGISTRY-}restaurantsapi
    build:
      context: .
      dockerfile: Services/Restaurants/Restaurants.API/Dockerfile
    depends_on: 
      - postgres
      - geocoding.api

  menu.api:
    image: ${DOCKER_REGISTRY-}menuapi
    build:
      context: .
      dockerfile: Services/Menu/Menu.API/Dockerfile
    depends_on:
      - postgres

  geocoding.api:
    image: ${DOCKER_REGISTRY-}geocodingapi
    build:
      context: .
      dockerfile: Services/Geocoding/Geocoding.API/Dockerfile
    depends_on:
      - redis
  
  management.ui:
    image: ${DOCKER_REGISTRY-}managementui
    build:
      context: ../web/restaurant-management/
      dockerfile: Dockerfile
    depends_on:
      - web.httpaggregator

  orders.ui:
    image: ${DOCKER_REGISTRY-}ordersui
    build:
      context: ../web/orders-app/
      dockerfile: Dockerfile
    depends_on:
      - web.httpaggregator

  restaurant.ui:
    image: ${DOCKER_REGISTRY-}restaurantui
    build:
      context: ../web/restaurant-service/
      dockerfile: Dockerfile
    depends_on:
      - web.httpaggregator

volumes:
  elasticsearch-data:
  postgres:  
  pgadmin_data:
