//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Core.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Core.Localization.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dish with name {0} already exist.
        /// </summary>
        public static string Dishes_Dish_with_name__0__already_exist {
            get {
                return ResourceManager.GetString("Dishes_Dish_with_name__0__already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity already exits.
        /// </summary>
        public static string Entities_Entity_already_exits {
            get {
                return ResourceManager.GetString("Entities_Entity_already_exits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity not found.
        /// </summary>
        public static string Entities_Entity_not_found {
            get {
                return ResourceManager.GetString("Entities_Entity_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity with id {0} not found.
        /// </summary>
        public static string Entities_Entity_with_id__0__not_found {
            get {
                return ResourceManager.GetString("Entities_Entity_with_id__0__not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu item for dish {0} already exist.
        /// </summary>
        public static string Menu_MenuItem_for_dish__0__already_exist {
            get {
                return ResourceManager.GetString("Menu_MenuItem_for_dish__0__already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant with location (latitude - {0}, longitude - {1} already exist.
        /// </summary>
        public static string Restaurants_Restaurant_with_location__latitude____0___longitude____1__already_exist {
            get {
                return ResourceManager.GetString("Restaurants_Restaurant_with_location__latitude____0___longitude____1__already_exi" +
                        "st", resourceCulture);
            }
        }
    }
}
